name: dyno_mvp
description: dyno mpv Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.5.1
  pin_input_text_field: ^4.4.0
  pin_code_fields: ^7.4.0
  google_fonts: ^4.0.3
  fluttertoast: ^8.2.1
  intl_phone_field: ^3.1.0
  logger:
  get_storage:
  flutter_date_pickers: ^0.4.1
  datetime_picker_formfield_new: ^2.1.0
  flutter_secure_storage: ^8.0.0
  jwt_decoder: ^2.0.1
  floating_bottom_navigation_bar: ^1.5.2
  image_picker: ^0.8.7
  http: ^0.13.3
  cached_network_image: ^3.0.0
  shared_preferences: ^2.0.20
  iconsax: ^0.0.8
  fl_chart: ^0.60.0
  floating_navbar: ^2.0.2
  qr_code_scanner: ^1.0.1
  barcode_widget: ^2.0.0
  qr_flutter: ^4.0.0
  animate_do: ^3.0.2
  bouncing_widget: ^2.0.0
  flutter_advanced_drawer: ^1.3.4
  align_positioned: ^3.0.0
  flutter_snake_navigationbar: ^0.6.1
  charts_flutter: ^0.11.0
  ionicons: ^0.2.2
  url_launcher: ^6.1.10








  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_svg: ^1.1.6
  pinput: ^2.2.21
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  raised_buttons: ^0.0.2

dev_dependencies:
  flutter_native_splash: ^2.2.17
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/employee.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  flutter_lints: ^2.0.0
flutter:


  uses-material-design: true

  assets:
    - assets/home/images/
    - assets/splash/
    - assets/register_images/
    - assets/onboard_images/
    - assets/Profile_images/
    - assets/
    - assets/logo/
    - assets/login/
    
