name: banking_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg:

  pinput: ^2.2.21
  localstorage: ^4.0.1+2
  http: ^0.13.5
  jwt_decoder: ^2.0.1
  get: ^4.6.5
  flutter_secure_storage: ^8.0.0
  get_storage: ^2.1.1
  pattern_formatter: ^2.0.0
  animate_do: ^3.0.2
  bouncing_widget: ^2.0.0
  flutter_advanced_drawer: ^1.3.4
  iconsax: ^0.0.8
  align_positioned: ^3.0.0
  ionicons: ^0.2.2
  shared_preferences: ^2.1.0
  getwidget: ^3.1.1
  fl_chart: ^0.62.0
  cupertino_icons: ^1.0.5
  qr_flutter: ^4.0.0
  google_fonts: ^4.0.3
  url_launcher: ^6.1.10
  video_player: ^2.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/cashier.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/login/
    - assets/onboard_images/
  

  